// This file is auto-generated by the generate-version npm script.
// Do not edit this file manually as changes will be overwritten.
module.exports = {
  version: require('./package.json').version
}; 